### ISSUE TITLE
Add usage info and improve validation of command line params passed to build-test.py

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#35]
If the wrong params are passed to build-test.py you get an ugly traceback:
```
cgdm-catania:et dunlap$ python3 esmf-test-scripts/build-test.py esmf-test-artifacts/
Traceback (most recent call last):
  File "esmf-test-scripts/build-test.py", line 263, in <module>
    main(sys.argv[1:])
  File "esmf-test-scripts/build-test.py", line 43, in main
    artifacts_root = sys.argv[2]
IndexError: list index out of range

```

We should have validation and also have a `build-test.py --help` option.

**Comment by ryanlong1004** [comment]
completed previously.
