### ISSUE TITLE
using this on cori

### ISSUE THREAD

**Issue by jedwards4b** [esmf-org/esmf-test-scripts#71]
I am trying to run this script on the cori haswell system at nersc.   For some reason the constraint defined
in cori.yaml is not being set in the submitted batch script.  Here is the script output, why isn't the 
constraint: haswell added to the batch script?

```
 python ./python_scripts/build-test.py ./config/cori.yaml /global/cscratch1/sd/jedwards/esmf_results/
reading ./config/cori.yaml
{'compiler': 'intel/19.0.3.199', 'netcdf': 'cray-netcdf/4.6.3.2', 'mpi': {'mpi': {'module': 'cray-mpich/7.7.10'}}, 'extra_env_vars': {'var1': 'ESMF_NETCDF_LIBS="-lnetcdf"', 'var2': 'ESMF_NETCDFF_LIBS="-lnetcdff"', 'var3': 'PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/cray/pe/hdf5/1.10.5.2/INTEL/19.0/lib/pkgconfig'}}
Cloning into 'intel_19.0.3_mpi_O_jedwards_pio_update2'...
remote: Enumerating objects: 300215, done.
remote: Counting objects: 100% (6203/6203), done.
remote: Compressing objects: 100% (2962/2962), done.
remote: Total 300215 (delta 4071), reused 4866 (delta 3220), pack-reused 294012
Receiving objects: 100% (300215/300215), 140.22 MiB | 16.86 MiB/s, done.
Resolving deltas: 100% (233556/233556), done.
Updating files: 100% (4769/4769), done.
Fetching origin
Already on 'jedwards/pio_update2'
Your branch is up to date with 'origin/jedwards/pio_update2'.
From github.com:esmf-org/esmf
 * branch                  jedwards/pio_update2 -> FETCH_HEAD
Already up to date.
Cloning into 'nuopc-app-prototypes'...
remote: Enumerating objects: 5982, done.
remote: Counting objects: 100% (5982/5982), done.
remote: Compressing objects: 100% (1548/1548), done.
remote: Total 5982 (delta 4618), reused 5714 (delta 4410), pack-reused 0
Receiving objects: 100% (5982/5982), 1.89 MiB | 3.52 MiB/s, done.
Resolving deltas: 100% (4618/4618), done.
status from nuopc clone command git clone -b develop git@github.com:esmf-org/nuopc-app-prototypes was 
sbatch build-intel_19.0.3_mpi_O.bat
sbatch: error: No architecture specified, cannot estimate job costs.
sbatch: error: Batch job submission failed: Unspecified error
Traceback (most recent call last):
  File "./python_scripts/build-test.py", line 590, in <module>
    main(sys.argv[1:])
  File "./python_scripts/build-test.py", line 422, in main
    subprocess.check_output(batch_build, shell=True)
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sbatch build-intel_19.0.3_mpi_O.bat' returned non-zero exit status 1.
```

**Comment by jedwards4b** [comment]
I've put a fix in my sandbox, adding constraint to the create_header arguments.  So I am running now, but I'm curious as to how this script works for you?

**Comment by ryanlong1004** [comment]
Necessary changes have been made to the cori.yaml config.

**Comment by ryanlong1004** [comment]
Closing, branch merged.
